version: "3.4"

x-common: &common
  volumes:
    - .:/src
    - airflow-home:/airflow
  env_file:
    - local.env

x-airflow: &airflow
  <<: *common
  build: .

services:

  web:
    <<: *airflow
    ports:
      - "80:80"
    depends_on:
      - postgres
      - rabbitmq

  scheduler:
    <<: *airflow
    command: scheduler

  worker:
    <<: *airflow
    command: worker

  rabbitmq:
    image: rabbitmq:management
    restart: always

  postgres:
    <<: *common
    image: postgres
    ports:
      - "5432:5432"


volumes:
  airflow-home: