version: "3.4"

x-common: &common
  volumes:
    - .:/src
    - airflow-home:/airflow
  env_file:
    - local.env

x-airflow: &airflow
  <<: *common
  build: .

services:

  web:
    <<: *airflow
    ports:
      - "80:80"

    depends_on:
      - postgres

  postgres:
    <<: *common
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - 5672

volumes:
  airflow-home: