version: "3.4"

x-common: &common
  volumes:
    - ./airflow_cdk/dags:/src/dags
    - airflow-home:/airflow
  env_file:
    - local.env

x-airflow: &airflow
  <<: *common
  build: .
  image: knowsuchagency/airflow-cdk

services:

  web:
    <<: *airflow
    ports:
      - "80:80"
    depends_on:
      - postgres
      - rabbitmq

  scheduler:
    <<: *airflow
    command: scheduler

  worker:
    <<: *airflow
    command: worker

  rabbitmq:
    image: rabbitmq:management
    restart: always
    ports:
    - 15672:15672

  flower:
    image: mher/flower
    env_file:
      - local.env
    ports:
      - 5555:5555
    depends_on:
      - rabbitmq

  postgres:
    <<: *common
    image: postgres
    ports:
      - "5432:5432"


volumes:
  airflow-home: